#!/usr/bin/env perl
# The table of STATEMENTS.md that maps each numbered statement of the paper to its Lean declarations
# and to its scripts with their recorded outputs, generated from the macros that paper/main.tex
# places right after each \label (they print nothing in the PDF):
#   \leanmap{A, B}        the Lean declarations of the statement, full names
#   \codemap{S > O, ...}  a script S of the repository with its recorded outputs O
#   \mapnote{text}        how the formal or computed result differs from the statement
# The numbers of the statements come from the aux file of a build of the paper. A numbered
# statement with no \leanmap is listed as not formalized; every path of a \codemap must exist.
#
# Usage, from the root of the repository, after a build of paper/main.tex (its aux file AUX):
#   perl code/paper/statement_map.pl AUX STATEMENTS.md           writes the table between the markers
#   perl code/paper/statement_map.pl --check AUX STATEMENTS.md   exit 1 if the table is not up to date
# The comparison ignores the padding of the table cells, so mdformat may align the table.
use strict;
use warnings;

my $check = @ARGV && $ARGV[0] eq '--check' ? shift @ARGV : '';
my ($aux, $readme) = @ARGV;
die "usage: statement_map.pl [--check] AUX STATEMENTS.md\n" unless defined $readme;

my $BEGIN = '<!-- statement-map begin: generated by code/paper/statement_map.pl, do not edit -->';
my $END   = '<!-- statement-map end -->';

# ---- numbers of the labels ---------------------------------------------------------------
my %num;
open my $ah, '<', $aux or die "$aux: $!";
while (<$ah>) { $num{$1} = $2 if /^\\newlabel\{([^}]+)\}\{\{([^}]*)\}/; }
close $ah;

# ---- the argument of a macro, with balanced braces ---------------------------------------
sub arg {
  my ($s, $i) = @_;    # $i at the opening brace
  my $d = 0;
  for my $j ($i .. length($s) - 1) {
    my $c = substr($s, $j, 1);
    $d++ if $c eq '{';
    if ($c eq '}' && --$d == 0) { return (substr($s, $i + 1, $j - $i - 1), $j + 1); }
  }
  die "unbalanced braces at offset $i\n";
}

my %kind = (theorem => 'Theorem', lemma => 'Lemma', proposition => 'Proposition',
  corollary => 'Corollary', definition => 'Definition', remark => 'Remark', step => 'Computation',
  question => 'Question', mainproposition => 'Proposition', maintheorem => 'Theorem', search => 'Search', section => 'Section', subsection => 'Section');
my $numbered = qr/theorem|lemma|proposition|corollary|definition|remark|step|question|mainproposition|maintheorem|search/;

sub rows {
  my ($file) = @_;
  open my $fh, '<', $file or die "$file: $!";
  my $src = do { local $/; <$fh> };
  close $fh;
  $src =~ s/(?<!\\)%[^\n]*//g;    # comments
  my (@rows, %seen);
  while ($src =~ /(\\begin\{($numbered)\}(?:\[[^\]]*\])?|\\(section|subsection)\*?\{)/g) {
    my ($env, $sec, $p) = ($2, $3, pos($src));
    if ($sec) { (undef, $p) = arg($src, $p - 1); }
    next unless substr($src, $p) =~ /^\s*\\label\{([^}]+)\}/;
    my $label = $1;
    $p += $+[0];
    my %m;
    while (substr($src, $p) =~ /^\s*\\(leanmap|codemap|mapnote)\{/) {
      my $name = $1;
      ($m{$name}, $p) = arg($src, $p + $+[0] - 1);
    }
    next if $sec && !%m;          # sections are listed only when they carry a map
    next if $seen{$label}++;
    my $n = $num{$label} // die "$label: no number in $aux\n";
    push @rows, [($kind{$env // $sec}) . " $n", $label, \%m];
  }
  return @rows;
}

sub md_math {    # $x$ as GitHub math, \ref{..} as its number
  my ($t) = @_;
  $t =~ s/\\ref\{([^}]+)\}/$num{$1} \/\/ die "$1: no number in $aux\n"/ge;
  $t =~ s/\\texttt\{([^}]*)\}/`$1`/g;
  $t =~ s/~/ /g;
  $t =~ s/\$([^\$]+)\$/\$`$1`\$/g;
  $t =~ s/\|/\\|/g;
  $t =~ s/\s+/ /g;
  $t =~ s/^ | $//g;
  return $t;
}

sub table {
  my @rows = @_;
  my @out = ('| statement | Lean | scripts and recorded outputs | note |', '| --- | --- | --- | --- |');
  for my $r (@rows) {
    my ($what, $label, $m) = @$r;
    my $lean = defined $m->{leanmap}
      ? join(', ', map { "`$_`" } grep { length } map { s/^\s+|\s+$//gr } split /,/, $m->{leanmap})
      : 'not formalized';
    my @code;
    for my $e (grep { length } map { s/^\s+|\s+$//gr } split /,/, $m->{codemap} // '') {
      my ($s, $o) = split /\s*>\s*/, $e, 2;
      my @paths = ($s, split(' ', $o // ''));
      -e $_ or die "$label: $_ does not exist\n" for @paths;
      my $link = sub { "[`$_[0]`]($_[0])" };
      push @code, $link->($s) . (defined $o ? ': ' . join(', ', map { $link->($_) } split(' ', $o)) : '');
    }
    my $note = md_math($m->{mapnote} // '');
    $note =~ s/^not formalized(?:; |$)// if $lean eq 'not formalized';
    push @out, join(' | ', "| $what", $lean, join('; ', @code), $note) . ' |';
  }
  return @out;
}

my @main = rows('paper/main.tex');
my @gen = ($BEGIN, '', table(@main), '', $END);

open my $rh, '<', $readme or die "$readme: $!";
my @lines = map { s/\n$//r } <$rh>;
close $rh;
my ($b) = grep { $lines[$_] eq $BEGIN } 0 .. $#lines;
my ($e) = grep { $lines[$_] eq $END } 0 .. $#lines;
die "$readme: the markers of the statement map are missing\n" unless defined $b && defined $e && $b < $e;

sub norm { my @l = @_; s/\s*\|\s*/|/g, s/-{3,}/---/g for @l; return join("\n", @l); }
if ($check) {
  my $ok = norm(@lines[$b .. $e]) eq norm(@gen);
  print $ok ? "statement map: up to date (" : "statement map: NOT up to date (", scalar(@main), " rows)\n";
  exit($ok ? 0 : 1);
}
splice @lines, $b, $e - $b + 1, @gen;
open my $wh, '>', $readme or die "$readme: $!";
print $wh map { "$_\n" } @lines;
close $wh;
print "statement map: ", scalar(@main), " rows written to $readme\n";
