import Tammes15.PaperSteps.Defs
import Tammes15.Attained.Data
import Tammes15.PaperSteps.FrameD

/-!
# Step (iii) of the proof of Proposition 7.7: the targets contain the frames

The eight target configurations of `TieData` are, point by point within their boxes, the frame
configurations of Section 2, and each of these is the image of `C1` or `C3` under an element of the
group `D` generated by `ρ(x, y, z) = (z, x, y)` and `τ(x, y, z) = (-z, -y, -x)`, up to the order of
its points (Proposition 2.1 (4)). Normalised by the program from two points of a contact,
the exact frame points are an orthogonal image of `C1` or `C3`. So Local of the program fires
`LocalFires` with `{frameC1, frameC3}` (`localFires_of_tieFires`).
-/

open Real Matrix
open scoped RealInnerProductSpace

namespace Tammes15.PaperSteps

open Tammes15 Attained

/-- Step (iii): Local of the program against the targets gives Local with `{C1, C3}`. -/
theorem localFires_of_tieFires {α : Type} {Y : α → E3} (h : TieFires Y) :
    LocalFires {Attained.frameC1, Attained.frameC3} Y := by
  obtain ⟨c, e, he, ab, hab, mirror, j, hz⟩ := h
  have hY := hz (fun i => pt bR uR (tieIdx c i)) (inTieBoxes_pt c)
  have hpt := pt_tieIdx c
  have hunit : ∀ i, ‖pt bR uR (tieIdx c i)‖ = 1 := by
    intro i
    rw [hpt, LinearIsometryEquiv.norm_map, frameX_unit]
  have key : ∀ e ∈ tieContacts c, ⟪pt bR uR (tieIdx c e.1), pt bR uR (tieIdx c e.2)⟫ = uR := by
    intro e he
    rw [hpt, hpt, LinearIsometryEquiv.inner_map_map]
    rcases tie_contacts c e he with h1 | h1
    · exact (frameX_contact (tieX c) _ h1).2
    · rw [real_inner_comm]
      exact (frameX_contact (tieX c) _ h1).2
  have hcon : ⟪pt bR uR (tieIdx c ab.1), pt bR uR (tieIdx c ab.2)⟫ = uR := by
    rcases hab with h | h <;> subst h
    · exact key ab he
    · rw [Prod.fst_swap, Prod.snd_swap, real_inner_comm]
      exact key e he
  have huR : |⟪pt bR uR (tieIdx c ab.1), pt bR uR (tieIdx c ab.2)⟫| < 1 := by
    have hb := bounds_of_mem uR uR_spec.1
    rw [hcon, abs_lt]
    constructor <;> linarith [hb.1, hb.2]
  obtain ⟨N, hN⟩ := normalize_isometry _ _ (hunit ab.1) (hunit ab.2) huR mirror
  refine ⟨frameX (tieX c), frameX_mem (tieX c), (dWord (tieG c)).trans N,
    j.trans (tieSigmaEquiv c), fun v => ?_⟩
  have hv := hY v
  rw [hN, hpt] at hv
  simpa [tieSigmaEquiv, LinearIsometryEquiv.trans_apply] using hv

end Tammes15.PaperSteps
