import Tammes15.Params.Generic
import Tammes15.Numerics.HexData

/-!
# The margin [3.4] on the 40 subintervals

Generated by code/lean-data/gen34.gp, which checks every rational witness exactly (gen34.out). For each `k`, the
bounds of `cos` and `sin` at `pa k / 2` give the three pieces of `P(pa k, h(pa k))` through `hrad_A_le`, `hrad_B_le`,
`le_sin_hrad` and `Pform_ge` (Generic.lean).
-/

open Real Tammes15.Numerics

namespace Tammes15.Params

theorem m34_0 : 6 * pa (0 + 1) < Pform (pa 0) (hrad (pa 0)) := by
  have hq : pa 0 = (357719 / 1200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (0 + 1) = (8597311 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 0 / 2 = (357719 / 2400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 0 := by rw [hq]; positivity
  have hl : pa 0 < π / 2 := by rw [hq]; linarith
  have he1 : (178471617 / 200000000 : ℝ) ≤ cos (pa 0 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 0 / 2) ≤ (446179043 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 0 / 2) ≤ (225664047 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (747653 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (186913 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (446179043 / 500000000 : ℝ) ^ 2) * (446179043 / 500000000 : ℝ) ^ 2 / (2 * (446179043 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (149447 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (747653 / 1000000 : ℝ) * (225664047 / 500000000 : ℝ) / (2 * (178471617 / 200000000 : ℝ) ^ 2 - 1) ≤ sin (60581 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_1 : 6 * pa (1 + 1) < Pform (pa 1) (hrad (pa 1)) := by
  have hq : pa 1 = (8597311 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (1 + 1) = (4304683 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 1 / 2 = (8597311 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 1 := by rw [hq]; positivity
  have hl : pa 1 < π / 2 := by rw [hq]; linarith
  have he1 : (111507643 / 125000000 : ℝ) ≤ cos (pa 1 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 1 / 2) ≤ (178412229 / 200000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 1 / 2) ≤ (2824467 / 6250000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (748511 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (74851 / 100000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (178412229 / 200000000 : ℝ) ^ 2) * (178412229 / 200000000 : ℝ) ^ 2 / (2 * (178412229 / 200000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (149959 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (748511 / 1000000 : ℝ) * (2824467 / 6250000 : ℝ) / (2 * (111507643 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (487 / 800 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_2 : 6 * pa (2 + 1) < Pform (pa 2) (hrad (pa 2)) := by
  have hq : pa 2 = (4304683 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (2 + 1) = (2873807 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 2 / 2 = (4304683 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 2 := by rw [hq]; positivity
  have hl : pa 2 < π / 2 := by rw [hq]; linarith
  have he1 : (891763819 / 1000000000 : ℝ) ≤ cos (pa 2 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 2 / 2) ≤ (44588191 / 50000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 2 / 2) ≤ (452501151 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (93671 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (749367 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (44588191 / 50000000 : ℝ) ^ 2) * (44588191 / 50000000 : ℝ) ^ 2 / (2 * (44588191 / 50000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (75237 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (93671 / 125000 : ℝ) * (452501151 / 1000000000 : ℝ) / (2 * (891763819 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (61171 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_3 : 6 * pa (3 + 1) < Pform (pa 3) (hrad (pa 3)) := by
  have hq : pa 3 = (2873807 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (3 + 1) = (2158369 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 3 / 2 = (2873807 / 19200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 3 := by rw [hq]; positivity
  have hl : pa 3 < π / 2 := by rw [hq]; linarith
  have he1 : (891466107 / 1000000000 : ℝ) ≤ cos (pa 3 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 3 / 2) ≤ (222866527 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 3 / 2) ≤ (226543693 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (46889 / 62500 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (750223 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (222866527 / 250000000 : ℝ) ^ 2) * (222866527 / 250000000 : ℝ) ^ 2 / (2 * (222866527 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (9437 / 6250 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (46889 / 62500 : ℝ) * (226543693 / 500000000 : ℝ) / (2 * (891466107 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (61469 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_4 : 6 * pa (4 + 1) < Pform (pa 4) (hrad (pa 4)) := by
  have hq : pa 4 = (2158369 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (4 + 1) = (8645531 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 4 / 2 = (2158369 / 14400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 4 := by rw [hq]; positivity
  have hl : pa 4 < π / 2 := by rw [hq]; linarith
  have he1 : (89116801 / 100000000 : ℝ) ≤ cos (pa 4 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 4 / 2) ≤ (891168011 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 4 / 2) ≤ (226836713 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (751079 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (375539 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (891168011 / 1000000000 : ℝ) ^ 2) * (891168011 / 1000000000 : ℝ) ^ 2 / (2 * (891168011 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (75757 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (751079 / 1000000 : ℝ) * (226836713 / 500000000 : ℝ) / (2 * (89116801 / 100000000 : ℝ) ^ 2 - 1) ≤ sin (61769 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_5 : 6 * pa (5 + 1) < Pform (pa 5) (hrad (pa 5)) := by
  have hq : pa 5 = (8645531 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (5 + 1) = (480977 / 1600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 5 / 2 = (8645531 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 5 := by rw [hq]; positivity
  have hl : pa 5 < π / 2 := by rw [hq]; linarith
  have he1 : (111358691 / 125000000 : ℝ) ≤ cos (pa 5 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 5 / 2) ≤ (890869529 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 5 / 2) ≤ (454259269 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (751933 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (187983 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (890869529 / 1000000000 : ℝ) ^ 2) * (890869529 / 1000000000 : ℝ) ^ 2 / (2 * (890869529 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (76019 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (751933 / 1000000 : ℝ) * (454259269 / 1000000000 : ℝ) / (2 * (111358691 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (62071 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_6 : 6 * pa (6 + 1) < Pform (pa 6) (hrad (pa 6)) := by
  have hq : pa 6 = (480977 / 1600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (6 + 1) = (8669641 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 6 / 2 = (480977 / 3200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 6 := by rw [hq]; positivity
  have hl : pa 6 < π / 2 := by rw [hq]; linarith
  have he1 : (890570661 / 1000000000 : ℝ) ≤ cos (pa 6 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 6 / 2) ≤ (445285331 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 6 / 2) ≤ (113711229 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (376393 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (150557 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (445285331 / 500000000 : ℝ) ^ 2) * (445285331 / 500000000 : ℝ) ^ 2 / (2 * (445285331 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (76283 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (376393 / 500000 : ℝ) * (113711229 / 250000000 : ℝ) / (2 * (890570661 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (499 / 800 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_7 : 6 * pa (7 + 1) < Pform (pa 7) (hrad (pa 7)) := by
  have hq : pa 7 = (8669641 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (7 + 1) = (271303 / 900000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 7 / 2 = (8669641 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 7 := by rw [hq]; positivity
  have hl : pa 7 < π / 2 := by rw [hq]; linarith
  have he1 : (890271409 / 1000000000 : ℝ) ≤ cos (pa 7 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 7 / 2) ≤ (89027141 / 100000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 7 / 2) ≤ (227715183 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (376819 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (753637 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (89027141 / 100000000 : ℝ) ^ 2) * (89027141 / 100000000 : ℝ) ^ 2 / (2 * (89027141 / 100000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (153097 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (376819 / 500000 : ℝ) * (227715183 / 500000000 : ℝ) / (2 * (890271409 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (62681 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_8 : 6 * pa (8 + 1) < Pform (pa 8) (hrad (pa 8)) := by
  have hq : pa 8 = (271303 / 900000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (8 + 1) = (2897917 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 8 / 2 = (271303 / 1800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 8 := by rw [hq]; positivity
  have hl : pa 8 < π / 2 := by rw [hq]; linarith
  have he1 : (222492943 / 250000000 : ℝ) ≤ cos (pa 8 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 8 / 2) ≤ (889971773 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 8 / 2) ≤ (456015619 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (75449 / 100000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (754489 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (889971773 / 1000000000 : ℝ) ^ 2) * (889971773 / 1000000000 : ℝ) ^ 2 / (2 * (889971773 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (153631 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (75449 / 100000 : ℝ) * (456015619 / 1000000000 : ℝ) / (2 * (222492943 / 250000000 : ℝ) ^ 2 - 1) ≤ sin (62989 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_9 : 6 * pa (9 + 1) < Pform (pa 9) (hrad (pa 9)) := by
  have hq : pa 9 = (2897917 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (9 + 1) = (4352903 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 9 / 2 = (2897917 / 19200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 9 := by rw [hq]; positivity
  have hl : pa 9 < π / 2 := by rw [hq]; linarith
  have he1 : (3558687 / 4000000 : ℝ) ≤ cos (pa 9 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 9 / 2) ≤ (889671751 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 9 / 2) ≤ (114150169 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (37767 / 50000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (755339 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (889671751 / 1000000000 : ℝ) ^ 2) * (889671751 / 1000000000 : ℝ) ^ 2 / (2 * (889671751 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (154169 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (37767 / 50000 : ℝ) * (114150169 / 250000000 : ℝ) / (2 * (3558687 / 4000000 : ℝ) ^ 2 - 1) ≤ sin (63299 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_10 : 6 * pa (10 + 1) < Pform (pa 10) (hrad (pa 10)) := by
  have hq : pa 10 = (4352903 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (10 + 1) = (8717861 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 10 / 2 = (4352903 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 10 := by rw [hq]; positivity
  have hl : pa 10 < π / 2 := by rw [hq]; linarith
  have he1 : (889371343 / 1000000000 : ℝ) ≤ cos (pa 10 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 10 / 2) ≤ (55585709 / 62500000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 10 / 2) ≤ (91437107 / 200000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (75619 / 100000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (756189 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (55585709 / 62500000 : ℝ) ^ 2) * (55585709 / 62500000 : ℝ) ^ 2 / (2 * (55585709 / 62500000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (15471 / 10000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (75619 / 100000 : ℝ) * (91437107 / 200000000 : ℝ) / (2 * (889371343 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (63611 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_11 : 6 * pa (11 + 1) < Pform (pa 11) (hrad (pa 11)) := by
  have hq : pa 11 = (8717861 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (11 + 1) = (727493 / 2400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 11 / 2 = (8717861 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 11 := by rw [hq]; positivity
  have hl : pa 11 < π / 2 := by rw [hq]; linarith
  have he1 : (111133819 / 125000000 : ℝ) ≤ cos (pa 11 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 11 / 2) ≤ (444535277 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 11 / 2) ≤ (114442549 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (378519 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (757037 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (444535277 / 500000000 : ℝ) ^ 2) * (444535277 / 500000000 : ℝ) ^ 2 / (2 * (444535277 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (77627 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (378519 / 500000 : ℝ) * (114442549 / 250000000 : ℝ) / (2 * (111133819 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (2557 / 4000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_12 : 6 * pa (12 + 1) < Pform (pa 12) (hrad (pa 12)) := by
  have hq : pa 12 = (727493 / 2400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (12 + 1) = (8741971 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 12 / 2 = (727493 / 4800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 12 := by rw [hq]; positivity
  have hl : pa 12 < π / 2 := by rw [hq]; linarith
  have he1 : (888769377 / 1000000000 : ℝ) ≤ cos (pa 12 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 12 / 2) ≤ (444384689 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 12 / 2) ≤ (458354659 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (378943 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (151577 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (444384689 / 500000000 : ℝ) ^ 2) * (444384689 / 500000000 : ℝ) ^ 2 / (2 * (444384689 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (77901 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (378943 / 500000 : ℝ) * (458354659 / 1000000000 : ℝ) / (2 * (888769377 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (64241 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_13 : 6 * pa (13 + 1) < Pform (pa 13) (hrad (pa 13)) := by
  have hq : pa 13 = (8741971 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (13 + 1) = (4377013 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 13 / 2 = (8741971 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 13 := by rw [hq]; positivity
  have hl : pa 13 < π / 2 := by rw [hq]; linarith
  have he1 : (444233909 / 500000000 : ℝ) ≤ cos (pa 13 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 13 / 2) ≤ (888467819 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 13 / 2) ≤ (114734731 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (758733 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (189683 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (888467819 / 1000000000 : ℝ) ^ 2) * (888467819 / 1000000000 : ℝ) ^ 2 / (2 * (888467819 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (156353 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (758733 / 1000000 : ℝ) * (114734731 / 250000000 : ℝ) / (2 * (444233909 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (807 / 1250 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_14 : 6 * pa (14 + 1) < Pform (pa 14) (hrad (pa 14)) := by
  have hq : pa 14 = (4377013 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (14 + 1) = (974009 / 3200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 14 / 2 = (4377013 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 14 := by rw [hq]; positivity
  have hl : pa 14 < π / 2 := by rw [hq]; linarith
  have he1 : (444082937 / 500000000 : ℝ) ≤ cos (pa 14 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 14 / 2) ≤ (7105327 / 8000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 14 / 2) ≤ (459522991 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (759579 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (379789 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (7105327 / 8000000 : ℝ) ^ 2) * (7105327 / 8000000 : ℝ) ^ 2 / (2 * (7105327 / 8000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (39227 / 25000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (759579 / 1000000 : ℝ) * (459522991 / 1000000000 : ℝ) / (2 * (444082937 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (811 / 1250 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_15 : 6 * pa (15 + 1) < Pform (pa 15) (hrad (pa 15)) := by
  have hq : pa 15 = (974009 / 3200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (15 + 1) = (1097267 / 3600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 15 / 2 = (974009 / 6400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 15 := by rw [hq]; positivity
  have hl : pa 15 < π / 2 := by rw [hq]; linarith
  have he1 : (887863547 / 1000000000 : ℝ) ≤ cos (pa 15 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 15 / 2) ≤ (221965887 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 15 / 2) ≤ (460106859 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (95053 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (760423 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (221965887 / 250000000 : ℝ) ^ 2) * (221965887 / 250000000 : ℝ) ^ 2 / (2 * (221965887 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (157467 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (95053 / 125000 : ℝ) * (460106859 / 1000000000 : ℝ) / (2 * (887863547 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (65203 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_16 : 6 * pa (16 + 1) < Pform (pa 16) (hrad (pa 16)) := by
  have hq : pa 16 = (1097267 / 3600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (16 + 1) = (8790191 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 16 / 2 = (1097267 / 7200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 16 := by rw [hq]; positivity
  have hl : pa 16 < π / 2 := by rw [hq]; linarith
  have he1 : (177512167 / 200000000 : ℝ) ≤ cos (pa 16 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 16 / 2) ≤ (221890209 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 16 / 2) ≤ (460690529 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (190317 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (761267 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (221890209 / 250000000 : ℝ) ^ 2) * (221890209 / 250000000 : ℝ) ^ 2 / (2 * (221890209 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (158029 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (190317 / 250000 : ℝ) * (460690529 / 1000000000 : ℝ) / (2 * (177512167 / 200000000 : ℝ) ^ 2 - 1) ≤ sin (8191 / 12500 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_17 : 6 * pa (17 + 1) < Pform (pa 17) (hrad (pa 17)) := by
  have hq : pa 17 = (8790191 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (17 + 1) = (1467041 / 4800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 17 / 2 = (8790191 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 17 := by rw [hq]; positivity
  have hl : pa 17 < π / 2 := by rw [hq]; linarith
  have he1 : (44362887 / 50000000 : ℝ) ≤ cos (pa 17 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 17 / 2) ≤ (887257741 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 17 / 2) ≤ (461273999 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (762111 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (76211 / 100000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (887257741 / 1000000000 : ℝ) ^ 2) * (887257741 / 1000000000 : ℝ) ^ 2 / (2 * (887257741 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (31719 / 20000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (762111 / 1000000 : ℝ) * (461273999 / 1000000000 : ℝ) / (2 * (44362887 / 50000000 : ℝ) ^ 2 - 1) ≤ sin (13171 / 20000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_18 : 6 * pa (18 + 1) < Pform (pa 18) (hrad (pa 18)) := by
  have hq : pa 18 = (1467041 / 4800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (18 + 1) = (8814301 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 18 / 2 = (1467041 / 9600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 18 := by rw [hq]; positivity
  have hl : pa 18 < π / 2 := by rw [hq]; linarith
  have he1 : (443477131 / 500000000 : ℝ) ≤ cos (pa 18 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 18 / 2) ≤ (886954263 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 18 / 2) ≤ (461857269 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (762953 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (95369 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (886954263 / 1000000000 : ℝ) ^ 2) * (886954263 / 1000000000 : ℝ) ^ 2 / (2 * (886954263 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (31833 / 20000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (762953 / 1000000 : ℝ) * (461857269 / 1000000000 : ℝ) / (2 * (443477131 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (13237 / 20000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_19 : 6 * pa (19 + 1) < Pform (pa 19) (hrad (pa 19)) := by
  have hq : pa 19 = (8814301 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (19 + 1) = (2206589 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 19 / 2 = (8814301 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 19 := by rw [hq]; positivity
  have hl : pa 19 < π / 2 := by rw [hq]; linarith
  have he1 : (1108313 / 1250000 : ℝ) ≤ cos (pa 19 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 19 / 2) ≤ (886650401 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 19 / 2) ≤ (23122017 / 50000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (381897 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (763793 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (886650401 / 1000000000 : ℝ) ^ 2) * (886650401 / 1000000000 : ℝ) ^ 2 / (2 * (886650401 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (159739 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (381897 / 500000 : ℝ) * (23122017 / 50000000 : ℝ) / (2 * (1108313 / 1250000 : ℝ) ^ 2 - 1) ≤ sin (16629 / 25000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_20 : 6 * pa (20 + 1) < Pform (pa 20) (hrad (pa 20)) := by
  have hq : pa 20 = (2206589 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (20 + 1) = (2946137 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 20 / 2 = (2206589 / 14400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 20 := by rw [hq]; positivity
  have hl : pa 20 < π / 2 := by rw [hq]; linarith
  have he1 : (443173077 / 500000000 : ℝ) ≤ cos (pa 20 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 20 / 2) ≤ (177269231 / 200000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 20 / 2) ≤ (463023211 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (382317 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (764633 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (177269231 / 200000000 : ℝ) ^ 2) * (177269231 / 200000000 : ℝ) ^ 2 / (2 * (177269231 / 200000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (40079 / 25000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (382317 / 500000 : ℝ) * (463023211 / 1000000000 : ℝ) / (2 * (443173077 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (66851 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_21 : 6 * pa (21 + 1) < Pform (pa 21) (hrad (pa 21)) := by
  have hq : pa 21 = (2946137 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (21 + 1) = (4425233 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 21 / 2 = (2946137 / 19200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 21 := by rw [hq]; positivity
  have hl : pa 21 < π / 2 := by rw [hq]; linarith
  have he1 : (443020763 / 500000000 : ℝ) ≤ cos (pa 21 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 21 / 2) ≤ (886041527 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 21 / 2) ≤ (231802941 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (382737 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (765473 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (886041527 / 1000000000 : ℝ) ^ 2) * (886041527 / 1000000000 : ℝ) ^ 2 / (2 * (886041527 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (160897 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (382737 / 500000 : ℝ) * (231802941 / 500000000 : ℝ) / (2 * (443020763 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (67187 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_22 : 6 * pa (22 + 1) < Pform (pa 22) (hrad (pa 22)) := by
  have hq : pa 22 = (4425233 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (22 + 1) = (8862521 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 22 / 2 = (4425233 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 22 := by rw [hq]; positivity
  have hl : pa 22 < π / 2 := by rw [hq]; linarith
  have he1 : (442868257 / 500000000 : ℝ) ≤ cos (pa 22 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 22 / 2) ≤ (177147303 / 200000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 22 / 2) ≤ (464188353 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (95789 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (766311 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (177147303 / 200000000 : ℝ) ^ 2) * (177147303 / 200000000 : ℝ) ^ 2 / (2 * (177147303 / 200000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (161483 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (95789 / 125000 : ℝ) * (464188353 / 1000000000 : ℝ) / (2 * (442868257 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (33763 / 50000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_23 : 6 * pa (23 + 1) < Pform (pa 23) (hrad (pa 23)) := by
  have hq : pa 23 = (8862521 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (23 + 1) = (61629 / 200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 23 / 2 = (8862521 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 23 := by rw [hq]; positivity
  have hl : pa 23 < π / 2 := by rw [hq]; linarith
  have he1 : (11067889 / 12500000 : ℝ) ≤ cos (pa 23 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 23 / 2) ≤ (885431121 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 23 / 2) ≤ (464770623 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (15343 / 20000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (767149 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (885431121 / 1000000000 : ℝ) ^ 2) * (885431121 / 1000000000 : ℝ) ^ 2 / (2 * (885431121 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (20259 / 12500 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (15343 / 20000 : ℝ) * (464770623 / 1000000000 : ℝ) / (2 * (11067889 / 12500000 : ℝ) ^ 2 - 1) ≤ sin (16967 / 25000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_24 : 6 * pa (24 + 1) < Pform (pa 24) (hrad (pa 24)) := by
  have hq : pa 24 = (61629 / 200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (24 + 1) = (8886631 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 24 / 2 = (61629 / 400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 24 := by rw [hq]; positivity
  have hl : pa 24 < π / 2 := by rw [hq]; linarith
  have he1 : (885125343 / 1000000000 : ℝ) ≤ cos (pa 24 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 24 / 2) ≤ (27660167 / 31250000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 24 / 2) ≤ (116338173 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (383993 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (153597 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (27660167 / 31250000 : ℝ) ^ 2) * (27660167 / 31250000 : ℝ) ^ 2 / (2 * (27660167 / 31250000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (81333 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (383993 / 500000 : ℝ) * (116338173 / 250000000 : ℝ) / (2 * (885125343 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (17053 / 25000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_25 : 6 * pa (25 + 1) < Pform (pa 25) (hrad (pa 25)) := by
  have hq : pa 25 = (8886631 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (25 + 1) = (4449343 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 25 / 2 = (8886631 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 25 := by rw [hq]; positivity
  have hl : pa 25 < π / 2 := by rw [hq]; linarith
  have he1 : (884819183 / 1000000000 : ℝ) ≤ cos (pa 25 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 25 / 2) ≤ (55301199 / 62500000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 25 / 2) ≤ (465934559 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (384411 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (768821 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (55301199 / 62500000 : ℝ) ^ 2) * (55301199 / 62500000 : ℝ) ^ 2 / (2 * (55301199 / 62500000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (163263 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (384411 / 500000 : ℝ) * (465934559 / 1000000000 : ℝ) / (2 * (884819183 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (34279 / 50000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_26 : 6 * pa (26 + 1) < Pform (pa 26) (hrad (pa 26)) := by
  have hq : pa 26 = (4449343 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (26 + 1) = (2970247 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 26 / 2 = (4449343 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 26 := by rw [hq]; positivity
  have hl : pa 26 < π / 2 := by rw [hq]; linarith
  have he1 : (1382051 / 1562500 : ℝ) ≤ cos (pa 26 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 26 / 2) ≤ (884512641 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 26 / 2) ≤ (233258113 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (96207 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (153931 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (884512641 / 1000000000 : ℝ) ^ 2) * (884512641 / 1000000000 : ℝ) ^ 2 / (2 * (884512641 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (32773 / 20000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (96207 / 125000 : ℝ) * (233258113 / 500000000 : ℝ) / (2 * (1382051 / 1562500 : ℝ) ^ 2 - 1) ≤ sin (68907 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_27 : 6 * pa (27 + 1) < Pform (pa 27) (hrad (pa 27)) := by
  have hq : pa 27 = (2970247 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (27 + 1) = (2230699 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 27 / 2 = (2970247 / 19200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 27 := by rw [hq]; positivity
  have hl : pa 27 < π / 2 := by rw [hq]; linarith
  have he1 : (176841143 / 200000000 : ℝ) ≤ cos (pa 27 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 27 / 2) ≤ (221051429 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 27 / 2) ≤ (46709769 / 100000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (77049 / 100000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (770489 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (221051429 / 250000000 : ℝ) ^ 2) * (221051429 / 250000000 : ℝ) ^ 2 / (2 * (221051429 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (164471 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (77049 / 100000 : ℝ) * (46709769 / 100000000 : ℝ) / (2 * (176841143 / 200000000 : ℝ) ^ 2 - 1) ≤ sin (69259 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_28 : 6 * pa (28 + 1) < Pform (pa 28) (hrad (pa 28)) := by
  have hq : pa 28 = (2230699 / 7200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (28 + 1) = (8934851 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 28 / 2 = (2230699 / 14400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 28 := by rw [hq]; positivity
  have hl : pa 28 < π / 2 := by rw [hq]; linarith
  have he1 : (110487301 / 125000000 : ℝ) ≤ cos (pa 28 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 28 / 2) ≤ (883898409 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 28 / 2) ≤ (467678953 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (771323 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (385661 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (883898409 / 1000000000 : ℝ) ^ 2) * (883898409 / 1000000000 : ℝ) ^ 2 / (2 * (883898409 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (82541 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (771323 / 1000000 : ℝ) * (467678953 / 1000000000 : ℝ) / (2 * (110487301 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (69613 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_29 : 6 * pa (29 + 1) < Pform (pa 29) (hrad (pa 29)) := by
  have hq : pa 29 = (8934851 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (29 + 1) = (1491151 / 4800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 29 / 2 = (8934851 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 29 := by rw [hq]; positivity
  have hl : pa 29 < π / 2 := by rw [hq]; linarith
  have he1 : (883590719 / 1000000000 : ℝ) ≤ cos (pa 29 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 29 / 2) ≤ (2761221 / 3125000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 29 / 2) ≤ (234130007 / 500000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (386077 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (772153 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (2761221 / 3125000 : ℝ) ^ 2) * (2761221 / 3125000 : ℝ) ^ 2 / (2 * (2761221 / 3125000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (165697 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (386077 / 500000 : ℝ) * (234130007 / 500000000 : ℝ) / (2 * (883590719 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (6997 / 10000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_30 : 6 * pa (30 + 1) < Pform (pa 30) (hrad (pa 30)) := by
  have hq : pa 30 = (1491151 / 4800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (30 + 1) = (8958961 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 30 / 2 = (1491151 / 9600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 30 := by rw [hq]; positivity
  have hl : pa 30 < π / 2 := by rw [hq]; linarith
  have he1 : (110410331 / 125000000 : ℝ) ≤ cos (pa 30 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 30 / 2) ≤ (883282649 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 30 / 2) ≤ (58605109 / 125000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (154597 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (96623 / 125000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (883282649 / 1000000000 : ℝ) ^ 2) * (883282649 / 1000000000 : ℝ) ^ 2 / (2 * (883282649 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (41579 / 25000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (154597 / 200000 : ℝ) * (58605109 / 125000000 : ℝ) / (2 * (110410331 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (70329 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_31 : 6 * pa (31 + 1) < Pform (pa 31) (hrad (pa 31)) := by
  have hq : pa 31 = (8958961 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (31 + 1) = (1121377 / 3600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 31 / 2 = (8958961 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 31 := by rw [hq]; positivity
  have hl : pa 31 < π / 2 := by rw [hq]; linarith
  have he1 : (176594839 / 200000000 : ℝ) ≤ cos (pa 31 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 31 / 2) ≤ (220743549 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 31 / 2) ≤ (469421527 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (154763 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (386907 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (220743549 / 250000000 : ℝ) ^ 2) * (220743549 / 250000000 : ℝ) ^ 2 / (2 * (220743549 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (8347 / 5000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (154763 / 200000 : ℝ) * (469421527 / 1000000000 : ℝ) / (2 * (176594839 / 200000000 : ℝ) ^ 2 - 1) ≤ sin (70691 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_32 : 6 * pa (32 + 1) < Pform (pa 32) (hrad (pa 32)) := by
  have hq : pa 32 = (1121377 / 3600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (32 + 1) = (998119 / 3200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 32 / 2 = (1121377 / 7200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 32 := by rw [hq]; positivity
  have hl : pa 32 < π / 2 := by rw [hq]; linarith
  have he1 : (882665361 / 1000000000 : ℝ) ≤ cos (pa 32 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 32 / 2) ≤ (441332681 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 32 / 2) ≤ (23500099 / 50000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (193661 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (774643 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (441332681 / 500000000 : ℝ) ^ 2) * (441332681 / 500000000 : ℝ) ^ 2 / (2 * (441332681 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (10473 / 6250 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (193661 / 250000 : ℝ) * (23500099 / 50000000 : ℝ) / (2 * (882665361 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (71057 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_33 : 6 * pa (33 + 1) < Pform (pa 33) (hrad (pa 33)) := by
  have hq : pa 33 = (998119 / 3200000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (33 + 1) = (4497563 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 33 / 2 = (998119 / 6400000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 33 := by rw [hq]; positivity
  have hl : pa 33 < π / 2 := by rw [hq]; linarith
  have he1 : (55147259 / 62500000 : ℝ) ≤ cos (pa 33 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 33 / 2) ≤ (176471229 / 200000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 33 / 2) ≤ (470582229 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (48467 / 62500 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (775471 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (176471229 / 200000000 : ℝ) ^ 2) * (176471229 / 200000000 : ℝ) ^ 2 / (2 * (176471229 / 200000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (168201 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (48467 / 62500 : ℝ) * (470582229 / 1000000000 : ℝ) / (2 * (55147259 / 62500000 : ℝ) ^ 2 - 1) ≤ sin (2232 / 3125 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_34 : 6 * pa (34 + 1) < Pform (pa 34) (hrad (pa 34)) := by
  have hq : pa 34 = (4497563 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (34 + 1) = (9007181 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 34 / 2 = (4497563 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 34 := by rw [hq]; positivity
  have hl : pa 34 < π / 2 := by rw [hq]; linarith
  have he1 : (882046547 / 1000000000 : ℝ) ≤ cos (pa 34 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 34 / 2) ≤ (220511637 / 250000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 34 / 2) ≤ (18846491 / 40000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (776299 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (388149 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (220511637 / 250000000 : ℝ) ^ 2) * (220511637 / 250000000 : ℝ) ^ 2 / (2 * (220511637 / 250000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (168839 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (776299 / 1000000 : ℝ) * (18846491 / 40000000 : ℝ) / (2 * (882046547 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (14359 / 20000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_35 : 6 * pa (35 + 1) < Pform (pa 35) (hrad (pa 35)) := by
  have hq : pa 35 = (9007181 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (35 + 1) = (751603 / 2400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 35 / 2 = (9007181 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 35 := by rw [hq]; positivity
  have hl : pa 35 < π / 2 := by rw [hq]; linarith
  have he1 : (110217071 / 125000000 : ℝ) ≤ cos (pa 35 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 35 / 2) ≤ (881736569 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 35 / 2) ≤ (471742117 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (194281 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (777123 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (881736569 / 1000000000 : ℝ) ^ 2) * (881736569 / 1000000000 : ℝ) ^ 2 / (2 * (881736569 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (84741 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (194281 / 250000 : ℝ) * (471742117 / 1000000000 : ℝ) / (2 * (110217071 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (72169 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_36 : 6 * pa (36 + 1) < Pform (pa 36) (hrad (pa 36)) := by
  have hq : pa 36 = (751603 / 2400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (36 + 1) = (9031291 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 36 / 2 = (751603 / 4800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 36 := by rw [hq]; positivity
  have hl : pa 36 < π / 2 := by rw [hq]; linarith
  have he1 : (881426207 / 1000000000 : ℝ) ≤ cos (pa 36 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 36 / 2) ≤ (27544569 / 31250000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 36 / 2) ≤ (94464351 / 200000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (777949 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (194487 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (27544569 / 31250000 : ℝ) ^ 2) * (27544569 / 31250000 : ℝ) ^ 2 / (2 * (27544569 / 31250000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (17013 / 10000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (777949 / 1000000 : ℝ) * (94464351 / 200000000 : ℝ) / (2 * (881426207 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (14509 / 20000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_37 : 6 * pa (37 + 1) < Pform (pa 37) (hrad (pa 37)) := by
  have hq : pa 37 = (9031291 / 28800000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (37 + 1) = (4521673 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 37 / 2 = (9031291 / 57600000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 37 := by rw [hq]; positivity
  have hl : pa 37 < π / 2 := by rw [hq]; linarith
  have he1 : (440557733 / 500000000 : ℝ) ≤ cos (pa 37 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 37 / 2) ≤ (881115467 / 1000000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 37 / 2) ≤ (472901189 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (778773 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (194693 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (881115467 / 1000000000 : ℝ) ^ 2) * (881115467 / 1000000000 : ℝ) ^ 2 / (2 * (881115467 / 1000000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (85391 / 50000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (778773 / 1000000 : ℝ) * (472901189 / 1000000000 : ℝ) / (2 * (440557733 / 500000000 : ℝ) ^ 2 - 1) ≤ sin (2917 / 4000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_38 : 6 * pa (38 + 1) < Pform (pa 38) (hrad (pa 38)) := by
  have hq : pa 38 = (4521673 / 14400000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (38 + 1) = (3018467 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 38 / 2 = (4521673 / 28800000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 38 := by rw [hq]; positivity
  have hl : pa 38 < π / 2 := by rw [hq]; linarith
  have he1 : (110100543 / 125000000 : ℝ) ≤ cos (pa 38 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 38 / 2) ≤ (176160869 / 200000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 38 / 2) ≤ (473480419 / 1000000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (194899 / 250000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (155919 / 200000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (176160869 / 200000000 : ℝ) ^ 2) * (176160869 / 200000000 : ℝ) ^ 2 / (2 * (176160869 / 200000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (2143 / 1250 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (194899 / 250000 : ℝ) * (473480419 / 1000000000 : ℝ) / (2 * (110100543 / 125000000 : ℝ) ^ 2 - 1) ≤ sin (18327 / 25000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

theorem m34_39 : 6 * pa (39 + 1) < Pform (pa 39) (hrad (pa 39)) := by
  have hq : pa 39 = (3018467 / 9600000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hq1 : pa (39 + 1) = (141679 / 450000 : ℝ) * π := by unfold pa dlo dhi; push_cast; ring
  have hh : pa 39 / 2 = (3018467 / 19200000 : ℝ) * π := by rw [hq]; ring
  have hπ0 := Real.pi_pos
  have hl0 : 0 < pa 39 := by rw [hq]; positivity
  have hl : pa 39 < π / 2 := by rw [hq]; linarith
  have he1 : (880492841 / 1000000000 : ℝ) ≤ cos (pa 39 / 2) := by
    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have he2 : cos (pa 39 / 2) ≤ (440246421 / 500000000 : ℝ) := by
    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
    simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hf2 : sin (pa 39 / 2) ≤ (118514861 / 250000000 : ℝ) := by
    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
    simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num
  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)
  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := (780419 / 1000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hs := le_sin_hrad hl0 hl he2 (s1 := (390209 / 500000 : ℝ)) (by norm_num) (by norm_num) (by norm_num)
  have hx : 1 - (2 - 2 * (440246421 / 500000000 : ℝ) ^ 2) * (440246421 / 500000000 : ℝ) ^ 2 / (2 * (440246421 / 500000000 : ℝ) ^ 2 - 1) ^ 2 ≤ cos (172103 / 100000 : ℝ) :=
    le_cos_of_cosT 8 (by norm_num) (by simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have hy : (780419 / 1000000 : ℝ) * (118514861 / 250000000 : ℝ) / (2 * (880492841 / 1000000000 : ℝ) ^ 2 - 1) ≤ sin (73693 / 100000 : ℝ) :=
    le_sin_of_sinT 8 (by norm_num) (by simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num)
  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)
    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)
  rw [hq1]
  linarith [pi_le_hi, key]

/-- [3.4]: `P(a, h(a)) - 6 b > 0` on the 40 subintervals `[a, b] = [pa k, pa (k + 1)]` of `[dlo, dhi]`. -/
theorem margin_onehex_P' (k : ℕ) (hk : k < 40) : 6 * pa (k + 1) < Pform (pa k) (hrad (pa k)) := by
  interval_cases k
  · exact m34_0
  · exact m34_1
  · exact m34_2
  · exact m34_3
  · exact m34_4
  · exact m34_5
  · exact m34_6
  · exact m34_7
  · exact m34_8
  · exact m34_9
  · exact m34_10
  · exact m34_11
  · exact m34_12
  · exact m34_13
  · exact m34_14
  · exact m34_15
  · exact m34_16
  · exact m34_17
  · exact m34_18
  · exact m34_19
  · exact m34_20
  · exact m34_21
  · exact m34_22
  · exact m34_23
  · exact m34_24
  · exact m34_25
  · exact m34_26
  · exact m34_27
  · exact m34_28
  · exact m34_29
  · exact m34_30
  · exact m34_31
  · exact m34_32
  · exact m34_33
  · exact m34_34
  · exact m34_35
  · exact m34_36
  · exact m34_37
  · exact m34_38
  · exact m34_39

end Tammes15.Params
