import Tammes15.Attained.Roots
import Tammes15.Attained.Points
import Tammes15.Attained.Ident
import Tammes15.Attained.Sep

/-!
# D4 for the frames C1 and C3

`attained : AttainedHyp {frameC1, frameC3}`: both frames are 15 unit vectors whose 30 listed pairs
have inner product exactly `uR`, the root of the quintic, and whose other pairs have inner product at
most `uR`. The case lemmas are the generated `nm_k`, `ct_k1_k2`, `sp_k1_k2` at `(bR, uR)`.
-/

set_option maxHeartbeats 400000

open scoped RealInnerProductSpace

namespace Tammes15.Attained

theorem frameC1_S_ne : ∀ ij ∈ frameC1.S, ij.1 ≠ ij.2 := by
  unfold frameC1; set_option maxRecDepth 200000 in decide

theorem frameC3_S_ne : ∀ ij ∈ frameC3.S, ij.1 ≠ ij.2 := by
  unfold frameC3; set_option maxRecDepth 200000 in decide

theorem frameC1_unit : ∀ i, ‖frameC1.p i‖ = 1 := by
  intro i
  fin_cases i
  · exact norm_pt bR uR 0 (nm_0 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 1 (nm_1 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 2 (nm_2 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 3 (nm_3 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 4 (nm_4 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 5 (nm_5 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 6 (nm_6 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 7 (nm_7 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 10 (nm_10 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 12 (nm_12 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 13 (nm_13 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 14 (nm_14 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 15 (nm_15 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 16 (nm_16 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR 17 (nm_17 bR uR uR_spec.2 bR_spec.2)

theorem frameC1_contact : ∀ ij ∈ frameC1.S,
    ij.1 ≠ ij.2 ∧ ⟪frameC1.p ij.1, frameC1.p ij.2⟫ = uR := by
  intro ij hij
  refine ⟨frameC1_S_ne ij hij, ?_⟩
  dsimp [frameC1] at hij ⊢
  simp only [Finset.mem_insert, Finset.mem_singleton] at hij
  rcases hij with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact inner_eq_of_num bR uR (keepC1 0) (keepC1 1) (ct_0_1 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 0) (keepC1 2) (ct_0_2 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 0) (keepC1 3) (ct_0_3 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 0) (keepC1 5) (ct_0_5 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 0) (keepC1 6) (ct_0_6 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 1) (keepC1 2) (ct_1_2 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 1) (keepC1 3) (ct_1_3 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 1) (keepC1 4) (ct_1_4 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 1) (keepC1 7) (ct_1_7 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 2) (keepC1 4) (ct_2_4 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 2) (keepC1 5) (ct_2_5 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 3) (keepC1 7) (ct_3_7 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 3) (keepC1 9) (ct_3_12 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 4) (keepC1 8) (ct_4_10 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 4) (keepC1 11) (ct_4_14 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 5) (keepC1 6) (ct_5_6 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 5) (keepC1 10) (ct_5_13 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 6) (keepC1 9) (ct_6_12 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 7) (keepC1 11) (ct_7_14 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 8) (keepC1 10) (ct_10_13 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 8) (keepC1 14) (ct_10_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 9) (keepC1 12) (ct_12_15 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 9) (keepC1 13) (ct_12_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 10) (keepC1 13) (ct_13_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 10) (keepC1 14) (ct_13_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 11) (keepC1 12) (ct_14_15 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 11) (keepC1 14) (ct_14_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 12) (keepC1 13) (ct_15_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 12) (keepC1 14) (ct_15_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR (keepC1 13) (keepC1 14) (ct_16_17 bR uR uR_spec.2 bR_spec.2)

theorem frameC1_sep : ∀ i j, i ≠ j → ⟪frameC1.p i, frameC1.p j⟫ ≤ uR := by
  refine sep_of_lt bR uR keepC1 ?_
  intro i j hij
  fin_cases i <;> fin_cases j
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_1 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_2 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_3 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_0_4 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_5 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_6 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_0_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_2 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_3 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_4 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_1_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_6 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_7 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_1_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_2_3 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_2_4 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_2_5 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_2_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_3_4 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_6 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_3_7 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_3_10 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_3_12 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_3_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_4_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_7 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_4_10 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_4_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_13 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_4_14 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_4_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_5_6 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_5_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_12 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_5_13 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_5_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_6_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_10 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_6_12 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_6_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_7_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_13 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_7_14 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_7_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_10_12 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_10_13 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_10_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_10_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_10_16 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_10_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_12_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_12_14 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_12_15 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_12_16 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_12_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_13_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_13_15 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_13_16 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_13_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_14_15 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_14_16 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_14_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_15_16 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_15_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_16_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)

theorem frameC3_unit : ∀ i, ‖frameC3.p i‖ = 1 := by
  intro i
  fin_cases i
  · exact norm_pt bR uR (keepC3 0) (nm_0 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 1) (nm_1 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 2) (nm_2 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 3) (nm_3 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 4) (nm_4 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 5) (nm_5 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 6) (nm_6 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 7) (nm_7 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 8) (nm_8 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 9) (nm_12 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 10) (nm_13 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 11) (nm_14 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 12) (nm_15 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 13) (nm_16 bR uR uR_spec.2 bR_spec.2)
  · exact norm_pt bR uR (keepC3 14) (nm_17 bR uR uR_spec.2 bR_spec.2)

theorem frameC3_contact : ∀ ij ∈ frameC3.S,
    ij.1 ≠ ij.2 ∧ ⟪frameC3.p ij.1, frameC3.p ij.2⟫ = uR := by
  intro ij hij
  refine ⟨frameC3_S_ne ij hij, ?_⟩
  simp only [frameC3, Finset.mem_insert, Finset.mem_singleton] at hij
  rcases hij with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact inner_eq_of_num bR uR _ _ (ct_0_1 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_0_2 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_0_3 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_0_5 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_0_6 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_1_2 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_1_3 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_1_4 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_1_7 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_2_4 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_2_5 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_2_8 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_3_7 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_3_12 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_4_8 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_4_14 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_5_6 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_5_13 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_6_12 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_7_14 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_8_13 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_12_15 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_12_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_13_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_13_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_14_15 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_14_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_15_16 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_15_17 bR uR uR_spec.2 bR_spec.2)
  · exact inner_eq_of_num bR uR _ _ (ct_16_17 bR uR uR_spec.2 bR_spec.2)

theorem frameC3_sep : ∀ i j, i ≠ j → ⟪frameC3.p i, frameC3.p j⟫ ≤ uR := by
  refine sep_of_lt bR uR keepC3 ?_
  intro i j hij
  fin_cases i <;> fin_cases j
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_1 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_2 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_3 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_0_4 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_5 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_0_6 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_0_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_0_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_2 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_3 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_4 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_1_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_6 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_1_7 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_1_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_1_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_2_3 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_2_4 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_2_5 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_2_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_7 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_2_8 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_2_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_2_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_3_4 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_6 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_3_7 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_3_8 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_3_12 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_3_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_3_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_4_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_7 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_4_8 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_4_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_13 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_4_14 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_4_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_4_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_5_6 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_5_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_12 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_5_13 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_5_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_5_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_6_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_8 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_6_12 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_6_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_6_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_7_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_13 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_7_14 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_7_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_7_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_8_12 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_8_13 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_8_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_8_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_8_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_8_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_12_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_12_14 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_12_15 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_12_16 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_12_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_le_of_num bR uR _ _ (sp_13_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_le_of_num bR uR _ _ (sp_13_15 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_13_16 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_13_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_14_15 bR uR uR_spec.2 bR_spec.2))
  · exact inner_le_of_num bR uR _ _ (sp_14_16 bR uR uR_spec.1 bR_spec.1)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_14_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_15_16 bR uR uR_spec.2 bR_spec.2))
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_15_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_16_17 bR uR uR_spec.2 bR_spec.2))
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)

theorem attained_of (hu : 1 / 2 < uR ∧ uR < 7 / 10) (hq : quintic uR = 0)
    (h1u : ∀ i, ‖frameC1.p i‖ = 1)
    (h1c : ∀ ij ∈ frameC1.S, ij.1 ≠ ij.2 ∧ ⟪frameC1.p ij.1, frameC1.p ij.2⟫ = uR)
    (h1s : ∀ i j, i ≠ j → ⟪frameC1.p i, frameC1.p j⟫ ≤ uR)
    (h3u : ∀ i, ‖frameC3.p i‖ = 1)
    (h3c : ∀ ij ∈ frameC3.S, ij.1 ≠ ij.2 ∧ ⟪frameC3.p ij.1, frameC3.p ij.2⟫ = uR)
    (h3s : ∀ i j, i ≠ j → ⟪frameC3.p i, frameC3.p j⟫ ≤ uR) :
    AttainedHyp {frameC1, frameC3} := by
  refine ⟨?_, uR, hu.1, hu.2, hq, ?_⟩
  · exact ⟨frameC1, by simp⟩
  · intro q hq_mem
    have hq_cases : q = frameC1 ∨ q = frameC3 := by
      simpa using hq_mem
    rcases hq_cases with (rfl | rfl)
    · exact ⟨h1u, h1c, h1s⟩
    · exact ⟨h3u, h3c, h3s⟩

/-- D4 for `F = {frameC1, frameC3}`. -/
theorem attained : AttainedHyp {frameC1, frameC3} :=
  attained_of (bounds_of_mem uR uR_spec.1) uR_spec.2 frameC1_unit frameC1_contact frameC1_sep
    frameC3_unit frameC3_contact frameC3_sep

end Tammes15.Attained
