import Tammes15.Attained.Frames
import Tammes15.Nonunique.Defs

/-!
# Strict separations of the frames C1 and C3

Generated by code/lean-data/gen_seplt.sh from Tammes15/Attained/Sep.lean and Frames.lean.
Every non-contact pair of C1 and C3 has inner product strictly below `uR`: `spl_k1_k2` is
`Tammes15.Attained.sp_k1_k2` with a strict inequality (same `dyadic_interval` proof), and
`frameC1_sep_lt`, `frameC3_sep_lt` follow the case split of `frameC1_sep`, `frameC3_sep`.
-/

set_option maxHeartbeats 0

open scoped RealInnerProductSpace

namespace Tammes15.Nonunique

open Tammes15 Tammes15.Attained

set_option linter.unusedSimpArgs false

theorem inner_lt_of_num (b u : ℝ) (k1 k2 : Fin 18)
    (h : ptN b u k1 0 * ptN b u k2 0 + ptN b u k1 1 * ptN b u k2 1 + ptN b u k1 2 * ptN b u k2 2 <
      (225008 * 225008 : ℝ) * u) : ⟪pt b u k1, pt b u k2⟫ < u := by
  rw [inner_pt, div_lt_iff₀ (by norm_num)]
  linarith

theorem spl_0_4 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * fN b u + bN b u * dN b u + cN b u * eN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_7 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * tN b u + bN b u * rN b u + cN b u * sN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * sN b u + bN b u * tN b u + cN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(rN b u)) + bN b u * (-(tN b u)) + cN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(fN b u)) + bN b u * (-(eN b u)) + cN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(eN b u)) + bN b u * (-(dN b u)) + cN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(dN b u)) + bN b u * (-(fN b u)) + cN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(cN b u)) + bN b u * (-(bN b u)) + cN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(bN b u)) + bN b u * (-(aN b u)) + cN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_0_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    aN b u * (-(aN b u)) + bN b u * (-(cN b u)) + cN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_5 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * eN b u + aN b u * fN b u + bN b u * dN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_6 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * rN b u + aN b u * sN b u + bN b u * tN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * sN b u + aN b u * tN b u + bN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(rN b u)) + aN b u * (-(tN b u)) + bN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(fN b u)) + aN b u * (-(eN b u)) + bN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(eN b u)) + aN b u * (-(dN b u)) + bN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(dN b u)) + aN b u * (-(fN b u)) + bN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(cN b u)) + aN b u * (-(bN b u)) + bN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(bN b u)) + aN b u * (-(aN b u)) + bN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_1_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    cN b u * (-(aN b u)) + aN b u * (-(cN b u)) + bN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_3 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * dN b u + cN b u * eN b u + aN b u * fN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_6 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * rN b u + cN b u * sN b u + aN b u * tN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_7 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * tN b u + cN b u * rN b u + aN b u * sN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(rN b u)) + cN b u * (-(tN b u)) + aN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(fN b u)) + cN b u * (-(eN b u)) + aN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(eN b u)) + cN b u * (-(dN b u)) + aN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(dN b u)) + cN b u * (-(fN b u)) + aN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(cN b u)) + cN b u * (-(bN b u)) + aN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(bN b u)) + cN b u * (-(aN b u)) + aN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_2_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    bN b u * (-(aN b u)) + cN b u * (-(cN b u)) + aN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_4 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * fN b u + eN b u * dN b u + fN b u * eN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_5 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * eN b u + eN b u * fN b u + fN b u * dN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_6 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * rN b u + eN b u * sN b u + fN b u * tN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * sN b u + eN b u * tN b u + fN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(rN b u)) + eN b u * (-(tN b u)) + fN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(eN b u)) + eN b u * (-(dN b u)) + fN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(dN b u)) + eN b u * (-(fN b u)) + fN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(cN b u)) + eN b u * (-(bN b u)) + fN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(bN b u)) + eN b u * (-(aN b u)) + fN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_3_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    dN b u * (-(aN b u)) + eN b u * (-(cN b u)) + fN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_5 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * eN b u + dN b u * fN b u + eN b u * dN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_6 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * rN b u + dN b u * sN b u + eN b u * tN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_7 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * tN b u + dN b u * rN b u + eN b u * sN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * (-(fN b u)) + dN b u * (-(eN b u)) + eN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * (-(eN b u)) + dN b u * (-(dN b u)) + eN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * (-(cN b u)) + dN b u * (-(bN b u)) + eN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * (-(bN b u)) + dN b u * (-(aN b u)) + eN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_4_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    fN b u * (-(aN b u)) + dN b u * (-(cN b u)) + eN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_7 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * tN b u + fN b u * rN b u + dN b u * sN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * sN b u + fN b u * tN b u + dN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(rN b u)) + fN b u * (-(tN b u)) + dN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(fN b u)) + fN b u * (-(eN b u)) + dN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(dN b u)) + fN b u * (-(fN b u)) + dN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(cN b u)) + fN b u * (-(bN b u)) + dN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(bN b u)) + fN b u * (-(aN b u)) + dN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_5_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    eN b u * (-(aN b u)) + fN b u * (-(cN b u)) + dN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_7 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * tN b u + sN b u * rN b u + tN b u * sN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * sN b u + sN b u * tN b u + tN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(rN b u)) + sN b u * (-(tN b u)) + tN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(eN b u)) + sN b u * (-(dN b u)) + tN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(dN b u)) + sN b u * (-(fN b u)) + tN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(cN b u)) + sN b u * (-(bN b u)) + tN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(bN b u)) + sN b u * (-(aN b u)) + tN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_6_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    rN b u * (-(aN b u)) + sN b u * (-(cN b u)) + tN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_8 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * sN b u + rN b u * tN b u + sN b u * rN b u < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_10 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(rN b u)) + rN b u * (-(tN b u)) + sN b u * (-(sN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(fN b u)) + rN b u * (-(eN b u)) + sN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(eN b u)) + rN b u * (-(dN b u)) + sN b u * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(cN b u)) + rN b u * (-(bN b u)) + sN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(bN b u)) + rN b u * (-(aN b u)) + sN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_7_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    tN b u * (-(aN b u)) + rN b u * (-(cN b u)) + sN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_8_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    sN b u * (-(fN b u)) + tN b u * (-(eN b u)) + rN b u * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_8_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    sN b u * (-(dN b u)) + tN b u * (-(fN b u)) + rN b u * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_8_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    sN b u * (-(cN b u)) + tN b u * (-(bN b u)) + rN b u * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_8_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    sN b u * (-(bN b u)) + tN b u * (-(aN b u)) + rN b u * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_8_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    sN b u * (-(aN b u)) + tN b u * (-(cN b u)) + rN b u * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_10_12 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(rN b u)) * (-(fN b u)) + (-(tN b u)) * (-(eN b u)) + (-(sN b u)) * (-(dN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_10_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(rN b u)) * (-(dN b u)) + (-(tN b u)) * (-(fN b u)) + (-(sN b u)) * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_10_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(rN b u)) * (-(cN b u)) + (-(tN b u)) * (-(bN b u)) + (-(sN b u)) * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_10_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(rN b u)) * (-(bN b u)) + (-(tN b u)) * (-(aN b u)) + (-(sN b u)) * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_12_13 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(fN b u)) * (-(eN b u)) + (-(eN b u)) * (-(dN b u)) + (-(dN b u)) * (-(fN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_12_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(fN b u)) * (-(dN b u)) + (-(eN b u)) * (-(fN b u)) + (-(dN b u)) * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_12_17 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(fN b u)) * (-(aN b u)) + (-(eN b u)) * (-(cN b u)) + (-(dN b u)) * (-(bN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_13_14 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(eN b u)) * (-(dN b u)) + (-(dN b u)) * (-(fN b u)) + (-(fN b u)) * (-(eN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_13_15 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(eN b u)) * (-(cN b u)) + (-(dN b u)) * (-(bN b u)) + (-(fN b u)) * (-(aN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem spl_14_16 (b u : ℝ) (hu : u ∈ Set.Icc ul uh) (hb : b ∈ Set.Icc bl bh) :
    (-(dN b u)) * (-(bN b u)) + (-(fN b u)) * (-(aN b u)) + (-(eN b u)) * (-(cN b u)) < (225008 * 225008 : ℝ) * u := by
  simp only [ul, uh, bl, bh] at hu hb
  simp only [aN, bN, cN, dN, eN, fN, rN, sN, tN]
  dyadic_interval [prec := 60]

theorem frameC1_sep_lt : ∀ i j : Fin 15, i < j → (i, j) ∉ S1 →
    ⟪frameC1.p i, frameC1.p j⟫ < uR := by
  intro i j hij hS
  show ⟪pt bR uR (keepC1 i), pt bR uR (keepC1 j)⟫ < uR
  fin_cases i <;> fin_cases j
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_0_4 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_0_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_1_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_6 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_1_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_2_3 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_2_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_3_4 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_6 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_3_10 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_3_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_4_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_7 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_4_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_13 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_4_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_5_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_12 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_5_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_6_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_10 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_6_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_7_10 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_13 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_7_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_10_12 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_10_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_10_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_10_16 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_12_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_12_14 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_12_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_13_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_13_15 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_14_16 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)

theorem frameC3_sep_lt : ∀ i j : Fin 15, i < j → (i, j) ∉ S3 →
    ⟪frameC3.p i, frameC3.p j⟫ < uR := by
  intro i j hij hS
  show ⟪pt bR uR (keepC3 i), pt bR uR (keepC3 j)⟫ < uR
  fin_cases i <;> fin_cases j
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_0_4 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_0_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_0_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_1_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_6 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_1_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_1_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_2_3 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_2_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_7 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_2_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_2_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_3_4 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_6 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_3_8 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_3_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_3_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_4_5 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_6 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_7 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_4_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_13 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_4_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_4_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_5_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_12 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_5_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_5_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_6_7 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_8 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_6_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_6_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_7_8 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_12 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_13 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_7_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_7_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_8_12 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_8_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_8_15 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_8_16 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_8_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_12_13 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_12_14 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_12_17 bR uR uR_spec.1 bR_spec.1)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact inner_lt_of_num bR uR _ _ (spl_13_14 bR uR uR_spec.1 bR_spec.1)
  · exact inner_lt_of_num bR uR _ _ (spl_13_15 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact inner_lt_of_num bR uR _ _ (spl_14_16 bR uR uR_spec.1 bR_spec.1)
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd (by decide) hS
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)
  · exact absurd hij (by decide)

end Tammes15.Nonunique
