\\ gen34.gp: witnesses and Lean proofs of the margin [3.4] on the 40 subintervals (Section 3.4 of the paper).
\\ For k < 40, l = pa k = q_k pi with q_k = (42926280 + 60275 k) / 144000000, and b = pa (k + 1) = q_(k+1) pi.
\\ Bounds, all rational and checked here exactly with the Taylor bounds of Numerics/Taylor.lean (n = 8):
\\   e1 <= cos (l/2) <= e2, sin (l/2) <= f2 (pi in [3.1415926535, 3.1415926536]);
\\   s1^2 <= 1 - (2 e2^2 - 1)^2 / e2^2, 1 - (2 e1^2 - 1)^2 / e1^2 <= s2^2 (bounds of sin h(l), Generic.lean);
\\   A = 1 - (2 - 2 e2^2) e2^2 / (2 e2^2 - 1)^2 <= cosLo x, B = s2 f2 / (2 e1^2 - 1) <= sinLo y, 2 y <= 3.1415926535;
\\   6 q_(k+1) 3.1415926536 < 2 x + 2 s1 (3.1415926535 - 2 y), so 6 b < P(l, h(l)) by Pform_ge.
\\ Writes the check lines to stdout and the Lean file to the path in the environment variable OUT (default:
\\ Tammes15/Params/Onehex.lean); code/lean-data/regen.sh compares it with the Lean file.
\\ Usage, from the repository root: gp -q code/lean-data/gen34.gp > code/lean-data/gen34.out
default(realprecision, 60);
cosT(n, x) = sum(k = 0, n - 1, (-1)^k * x^(2*k) / (2*k)!);
sinT(n, x) = sum(k = 0, n - 1, (-1)^k * x^(2*k+1) / (2*k+1)!);
cosUp(n, x) = cosT(n, x) + x^(2*n) / (2*n)!;
cosLo(n, x) = cosT(n, x) - x^(2*n) / (2*n)!;
sinUp(n, x) = sinT(n, x) + x^(2*n+1) / (2*n+1)!;
sinLo(n, x) = sinT(n, x) - x^(2*n+1) / (2*n+1)!;
up(x, D) = ceil(x * 10^D) / 10^D;
dn(x, D) = floor(x * 10^D) / 10^D;
plo = 31415926535 / 10^10; phi = 31415926536 / 10^10; n = 8;
out = getenv("OUT"); if (out == 0, out = "Tammes15/Params/Onehex.lean");
q(k) = (42926280 + 60275 * k) / 144000000;
L(s) = write(out, s);
fr(r) = Str("(", numerator(r), " / ", denominator(r), " : ℝ)");
simpc = "simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num";
simps = "simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]; norm_num";
system(Str("rm -f ", out));
L("import Tammes15.Params.Generic\nimport Tammes15.Numerics.HexData\n");
L("/-!\n# The margin [3.4] on the 40 subintervals\n");
L("Generated by code/lean-data/gen34.gp, which checks every rational witness exactly (gen34.out). For each `k`, the");
L("bounds of `cos` and `sin` at `pa k / 2` give the three pieces of `P(pa k, h(pa k))` through `hrad_A_le`, `hrad_B_le`,");
L("`le_sin_hrad` and `Pform_ge` (Generic.lean).\n-/\n");
L("open Real Tammes15.Numerics\n\nnamespace Tammes15.Params\n");
allok = 1; worst = 1;
{for (k = 0, 39,
  qk = q(k); q1 = q(k + 1); h = qk / 2;
  e1 = dn(cosLo(n, h * phi), 9); e2 = up(cosUp(n, h * plo), 9); f2 = up(sinUp(n, h * phi), 9);
  C2 = (2 * e2^2 - 1)^2 / e2^2; C1 = (2 * e1^2 - 1)^2 / e1^2;
  s1 = dn(sqrt(1 - C2), 6); s2 = up(sqrt(1 - C1), 6);
  A = 1 - (2 - 2 * e2^2) * e2^2 / (2 * e2^2 - 1)^2; x = dn(acos(A), 5) - 1 / 10^5;
  B = s2 * f2 / (2 * e1^2 - 1); y = up(asin(B), 5) + 1 / 10^5;
  lhs = 6 * q1 * phi; rhs = 2 * x + 2 * s1 * (plo - 2 * y);
  c = [e1 <= cosLo(n, h * phi), cosUp(n, h * plo) <= e2, sinUp(n, h * phi) <= f2, h * phi <= 3/2,
       0 < e1, 0 < 2 * e1^2 - 1, e2 <= 1, 0 < 2 * e2^2 - 1, 0 <= s1, s1^2 <= 1 - C2, 0 <= s2, 1 - C1 <= s2^2,
       0 <= x, A <= cosLo(n, x), 0 <= y, B <= sinLo(n, y), 2 * y <= plo, lhs < rhs];
  good = (vecmin(apply(t -> if (t, 1, 0), c)) == 1); if (!good, allok = 0);
  worst = min(worst, (rhs - lhs) * 1.);
  printf("k = %2d  %s  margin %.6f\n", k, if(good, "OK", "FAIL"), (rhs - lhs) * 1.);
  L(Str("theorem m34_", k, " : 6 * pa (", k, " + 1) < Pform (pa ", k, ") (hrad (pa ", k, ")) := by"));
  L(Str("  have hq : pa ", k, " = ", fr(qk), " * π := by unfold pa dlo dhi; push_cast; ring"));
  L(Str("  have hq1 : pa (", k, " + 1) = ", fr(q1), " * π := by unfold pa dlo dhi; push_cast; ring"));
  L(Str("  have hh : pa ", k, " / 2 = ", fr(h), " * π := by rw [hq]; ring"));
  L("  have hπ0 := Real.pi_pos");
  L(Str("  have hl0 : 0 < pa ", k, " := by rw [hq]; positivity"));
  L(Str("  have hl : pa ", k, " < π / 2 := by rw [hq]; linarith"));
  L(Str("  have he1 : ", fr(e1), " ≤ cos (pa ", k, " / 2) := by"));
  L("    rw [hh]; refine le_cos_mul_pi 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_");
  L(Str("    ", simpc));
  L(Str("  have he2 : cos (pa ", k, " / 2) ≤ ", fr(e2), " := by"));
  L("    rw [hh]; refine cos_mul_pi_le 8 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_");
  L(Str("    ", simpc));
  L(Str("  have hf2 : sin (pa ", k, " / 2) ≤ ", fr(f2), " := by"));
  L("    rw [hh]; refine sin_mul_pi_le 8 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_");
  L(Str("    ", simps));
  L("  have hA := hrad_A_le hl0 hl he1 he2 (by norm_num) (by norm_num) (by norm_num)");
  L(Str("  have hB := hrad_B_le hl0 hl he1 hf2 (s2 := ", fr(s2), ") (by norm_num) (by norm_num) (by norm_num) (by norm_num)"));
  L(Str("  have hs := le_sin_hrad hl0 hl he2 (s1 := ", fr(s1), ") (by norm_num) (by norm_num) (by norm_num)"));
  L(Str("  have hx : 1 - (2 - 2 * ", fr(e2), " ^ 2) * ", fr(e2), " ^ 2 / (2 * ", fr(e2), " ^ 2 - 1) ^ 2 ≤ cos ", fr(x), " :="));
  L(Str("    le_cos_of_cosT 8 (by norm_num) (by ", simpc, ")"));
  L(Str("  have hy : ", fr(s2), " * ", fr(f2), " / (2 * ", fr(e1), " ^ 2 - 1) ≤ sin ", fr(y), " :="));
  L(Str("    le_sin_of_sinT 8 (by norm_num) (by ", simps, ")"));
  L("  have key := Pform_ge (hA.trans hx) (by norm_num) (by linarith [pi_ge_lo]) (hB.trans hy) (by norm_num)");
  L("    (by linarith [pi_ge_lo]) hs (by norm_num) pi_ge_lo (by norm_num)");
  L("  rw [hq1]");
  L("  linarith [pi_le_hi, key]\n"));}
L("/-- [3.4]: `P(a, h(a)) - 6 b > 0` on the 40 subintervals `[a, b] = [pa k, pa (k + 1)]` of `[dlo, dhi]`. -/");
L("theorem margin_onehex_P' (k : ℕ) (hk : k < 40) : 6 * pa (k + 1) < Pform (pa k) (hrad (pa k)) := by");
L("  interval_cases k");
for (k = 0, 39, L(Str("  · exact m34_", k)));
L("\nend Tammes15.Params");
print(if(allok, "ALL OK", "SOME CHECK FAILED"), "; least margin ", worst);
quit;
