#!/bin/sh
# gen_seplt.sh [OUT]: writes Tammes15/Nonunique/SepLt.lean (or OUT), the strict separations of the frames C1 and C3,
# from Tammes15/Attained/Sep.lean and Frames.lean: the lemmas `spl_k1_k2` are the `sp_k1_k2` of Sep.lean with `≤`
# made `<` (same dyadic_interval proofs), and `frameC1_sep_lt`, `frameC3_sep_lt` follow the case split of
# `frameC1_sep`, `frameC3_sep` of Frames.lean: a listed pair contradicts the hypothesis `(i, j) ∉ S`, a separated
# pair uses `spl`. Run from the repository root; code/lean-data/regen.sh compares OUT with the Lean file.
set -e
A=Tammes15/Attained
O=${1:-Tammes15/Nonunique/SepLt.lean}
{
cat <<'H'
import Tammes15.Attained.Frames
import Tammes15.Nonunique.Defs

/-!
# Strict separations of the frames C1 and C3

Generated by code/lean-data/gen_seplt.sh from Tammes15/Attained/Sep.lean and Frames.lean.
Every non-contact pair of C1 and C3 has inner product strictly below `uR`: `spl_k1_k2` is
`Tammes15.Attained.sp_k1_k2` with a strict inequality (same `dyadic_interval` proof), and
`frameC1_sep_lt`, `frameC3_sep_lt` follow the case split of `frameC1_sep`, `frameC3_sep`.
-/

set_option maxHeartbeats 0

open scoped RealInnerProductSpace

namespace Tammes15.Nonunique

open Tammes15 Tammes15.Attained

set_option linter.unusedSimpArgs false

theorem inner_lt_of_num (b u : ℝ) (k1 k2 : Fin 18)
    (h : ptN b u k1 0 * ptN b u k2 0 + ptN b u k1 1 * ptN b u k2 1 + ptN b u k1 2 * ptN b u k2 2 <
      (225008 * 225008 : ℝ) * u) : ⟪pt b u k1, pt b u k2⟫ < u := by
  rw [inner_pt, div_lt_iff₀ (by norm_num)]
  linarith

H
awk '/^theorem sp_/{p=1} p{print} p&&/dyadic_interval/{print ""; p=0}' $A/Sep.lean |
  sed 's/^theorem sp_/theorem spl_/; s/≤ (225008 \* 225008 : ℝ) \* u := by$/< (225008 * 225008 : ℝ) * u := by/'
for F in C1 C3; do
  S=$(echo $F | sed 's/C/S/')
  echo "theorem frame${F}_sep_lt : ∀ i j : Fin 15, i < j → (i, j) ∉ $S →"
  echo "    ⟪frame$F.p i, frame$F.p j⟫ < uR := by"
  echo "  intro i j hij hS"
  echo "  show ⟪pt bR uR (keep$F i), pt bR uR (keep$F j)⟫ < uR"
  echo "  fin_cases i <;> fin_cases j"
  awk -v F=$F '$0 ~ "^theorem frame" F "_sep "{p=1; next} p&&/^  fin_cases/{q=1; next} p&&q&&/^  · /{print; next} p&&q{exit}' $A/Frames.lean |
    sed 's/^  · exact le_of_eq (inner_eq_of_num bR uR _ _ (ct_[0-9_]* bR uR uR_spec.2 bR_spec.2))$/  · exact absurd (by decide) hS/; s/^  · exact inner_le_of_num bR uR _ _ (sp_\([0-9_]*\) bR uR uR_spec.1 bR_spec.1)$/  · exact inner_lt_of_num bR uR _ _ (spl_\1 bR uR uR_spec.1 bR_spec.1)/'
  echo
done
echo "end Tammes15.Nonunique"
} > "$O"
echo "wrote $O: $(grep -c '^theorem spl_' "$O") spl lemmas, $(grep -c 'inner_lt_of_num bR' "$O") separated pairs, $(grep -c 'absurd (by decide) hS' "$O") listed pairs"
