#!/usr/bin/env bash
# The differential test of Tammes15/Contractors/Prims.lean against the program (Section 10.4 of the paper).
#
#   run.sh N        N cases per primitive (build first: setup.sh, then lake build in lean/)
#
# The Rust driver writes its stream (inputs, log of the arithmetic, results); the Lean driver reads
# it, evaluates the copy PrimsQ of Prims.lean on the same inputs with the logged arithmetic, and
# writes its own stream and the report. Neither stream is kept: their SHA-256 are, and both are
# regenerated by running this again (the inputs come from fixed seeds). Files in out/:
#   report-N.txt   mismatches, conflicts, per-primitive counts, the driver's summary
#   rust-N.err     the driver's stderr (CONFLICT and FLIP lines, summary)
#   lean-N.err     the Lean driver's stderr (a PANIC line per MISS: a call the program never made)
#   rust-N.sha256, lean-N.sha256   hashes of the two streams
#   time-N.txt     wall time
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
N=${1:?usage: run.sh N}
out=$here/out
mkdir -p "$out"
rust=$here/build/target/release/difftest
lean=$here/lean/.lake/build/bin/difftest
export LEAN_NUM_THREADS=1
fifo=$(mktemp -u /tmp/difftest-fifo.XXXXXX)
mkfifo "$fifo"
trap 'rm -f "$fifo"' EXIT
sha256sum < "$fifo" | sed 's/-$/rust stream/' > "$out/rust-$N.sha256" &
hpid=$!
start=$(date +%s)
"$rust" "$N" 2> "$out/rust-$N.err" | tee "$fifo" \
  | "$lean" "$out/report-$N.txt" 2> "$out/lean-$N.err" \
  | sha256sum | sed 's/-$/lean stream/' > "$out/lean-$N.sha256"
wait "$hpid"
end=$(date +%s)
echo "N=$N wall $((end - start)) s" > "$out/time-$N.txt"
echo "PANIC $(grep -c '^PANIC' "$out/lean-$N.err" || true)" >> "$out/report-$N.txt"
grep -E '^(TOTAL|PANIC)' "$out/report-$N.txt"
