import Tammes15.Numerics.HexData

/-!
# Enclosures for the extreme chord of Proposition onehex

Generated by code/lean/numerics/chord.gp (output chord.out), which checks every rational inequality below exactly:
lower bounds of `sin` at `dlo` and `dlo / 2`, and of `cos` and `sin` at the checkpoints of the step of the inscribed
polygon at the ends of `[dlo, dhi]` (paper, Proposition onehex, inscribed polygon form).
-/

open Real

namespace Tammes15.Numerics

theorem le_sin_hdpt_0 : 112832023/250000000 ≤ sin (357719/2400000 * π) := by
  refine le_sin_mul_pi 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_sin_dpt_0 : 12585821/15625000 ≤ sin (357719/1200000 * π) := by
  refine le_sin_mul_pi 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_chordGam : -113875993/200000000 ≤ cos (41569/60000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_chord3 : 749305453/1000000000 ≤ cos (18431/80000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_chord1 : 242759351/250000000 ≤ cos (18431/240000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_sin_chordG : 205999241/1000000000 ≤ sin (743/11250 * π) := by
  refine le_sin_mul_pi 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

end Tammes15.Numerics
