import Tammes15.Numerics.Taylor

/-!
# Enclosures of `cos` and `sin` at the points of the ten pieces of Proposition onehex

Generated by code/lean/numerics/pieces.gp (output pieces.out), which checks every rational inequality below
exactly. The points are `dpt j = q_j * π` with `q_j = (10731570 + 60275 j) / 36000000` (Rattlers/HexPoly.lean,
the subdivision of `[dlo, dhi]`), their halves, and the checkpoints `T1`, `G`, `(180 - G) / 2`, `T2` (in degrees)
of each piece (paper, Proposition onehex, inscribed polygon form). Each bound is a Taylor polynomial of order 20
or 21 with its Lagrange remainder at `q * 3.1415926535` or `q * 3.1415926536`, closed by `norm_num`.
-/

open Real

namespace Tammes15.Numerics

theorem pi_ge_lo : (3.1415926535 : ℝ) ≤ π := by
  have := Real.pi_gt_d20; norm_num at this ⊢; linarith

theorem pi_le_hi : π ≤ (3.1415926536 : ℝ) := by
  have := Real.pi_lt_d20; norm_num at this ⊢; linarith

theorem cos_dpt_le_0 : cos (357719/1200000 * π) ≤ 296302953/500000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_0 : 592605903/1000000000 ≤ cos (357719/1200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_0 : cos (357719/2400000 * π) ≤ 892358087/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_0 : 223089521/250000000 ≤ cos (357719/2400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_0 : sin (357719/2400000 * π) ≤ 90265619/200000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_1 : cos (2158369/7200000 * π) ≤ 36772553/62500000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_1 : 117672169/200000000 ≤ cos (2158369/7200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_1 : cos (2158369/14400000 * π) ≤ 222792003/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_1 : 891168009/1000000000 ≤ cos (2158369/14400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_1 : sin (2158369/14400000 * π) ≤ 453673427/1000000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_2 : cos (271303/900000 * π) ≤ 73012439/125000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_2 : 584099509/1000000000 ≤ cos (271303/900000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_2 : cos (271303/1800000 * π) ≤ 444985887/500000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_2 : 889971771/1000000000 ≤ cos (271303/1800000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_2 : sin (271303/1800000 * π) ≤ 22800781/50000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_3 : cos (727493/2400000 * π) ≤ 115964403/200000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_3 : 144955503/250000000 ≤ cos (727493/2400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_3 : cos (727493/4800000 * π) ≤ 888769379/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_3 : 27774043/31250000 ≤ cos (727493/4800000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_3 : sin (727493/4800000 * π) ≤ 22917733/50000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_4 : cos (1097267/3600000 * π) ≤ 143882119/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_4 : 575528473/1000000000 ≤ cos (1097267/3600000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_4 : cos (1097267/7200000 * π) ≤ 887560837/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_4 : 443780417/500000000 ≤ cos (1097267/7200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_4 : sin (1097267/7200000 * π) ≤ 46069053/100000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_5 : cos (2206589/7200000 * π) ≤ 285609507/500000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_5 : 571219011/1000000000 ≤ cos (2206589/7200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_5 : cos (2206589/14400000 * π) ≤ 221586539/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_5 : 886346153/1000000000 ≤ cos (2206589/14400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_5 : sin (2206589/14400000 * π) ≤ 115755803/250000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_6 : cos (61629/200000 * π) ≤ 566893747/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_6 : 35430859/62500000 ≤ cos (61629/200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_6 : cos (61629/400000 * π) ≤ 177025069/200000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_6 : 442562671/500000000 ≤ cos (61629/400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_6 : sin (61629/400000 * π) ≤ 465352693/1000000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_7 : cos (2230699/7200000 * π) ≤ 140638199/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_7 : 562552793/1000000000 ≤ cos (2230699/7200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_7 : cos (2230699/14400000 * π) ≤ 88389841/100000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_7 : 883898407/1000000000 ≤ cos (2230699/14400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_7 : sin (2230699/14400000 * π) ≤ 233839477/500000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_8 : cos (1121377/3600000 * π) ≤ 558196281/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_8 : 279098139/500000000 ≤ cos (1121377/3600000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_8 : cos (1121377/7200000 * π) ≤ 882665363/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_8 : 11033317/12500000 ≤ cos (1121377/7200000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_8 : sin (1121377/7200000 * π) ≤ 470001981/1000000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_9 : cos (751603/2400000 * π) ≤ 276912161/500000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_9 : 553824319/1000000000 ≤ cos (751603/2400000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_9 : cos (751603/4800000 * π) ≤ 881426209/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_9 : 440713103/500000000 ≤ cos (751603/4800000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_9 : sin (751603/4800000 * π) ≤ 118080439/250000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_dpt_le_10 : cos (141679/450000 * π) ≤ 6867963/12500000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_dpt_10 : 549437037/1000000000 ≤ cos (141679/450000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_hdpt_le_10 : cos (141679/900000 * π) ≤ 5501131/6250000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_hdpt_10 : 880180957/1000000000 ≤ cos (141679/900000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem sin_hdpt_le_10 : sin (141679/900000 * π) ≤ 94927653/200000000 := by
  refine sin_mul_pi_le 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [sinT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_0 : 49138837/500000000 ≤ cos (703/1500 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_0 : cos (125393/180000 * π) ≤ -28959079/50000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_0 : cos (54607/360000 * π) ≤ 177717843/200000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_0 : 939632911/1000000000 ≤ cos (667/6000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_1 : 38011467/500000000 ≤ cos (2141/4500 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_1 : cos (31523/45000 * π) ≤ -589083533/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_1 : cos (13477/90000 * π) ≤ 35654829/40000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_1 : 470262763/500000000 ≤ cos (331/3000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_2 : 53207403/1000000000 ≤ cos (1739/3600 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_2 : cos (126809/180000 * π) ≤ -74893671/125000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_2 : cos (53191/360000 * π) ≤ 894189403/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_2 : 188282339/200000000 ≤ cos (219/2000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_3 : 14920349/500000000 ≤ cos (981/2000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_3 : cos (63773/90000 * π) ≤ -19043693/31250000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_3 : cos (26227/180000 * π) ≤ 897050217/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_3 : 942349829/1000000000 ≤ cos (391/3600 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_4 : 5759553/1000000000 ≤ cos (2989/6000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_4 : cos (891/1250 * π) ≤ -77479227/125000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_4 : cos (359/2500 * π) ≤ 899953839/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_4 : 188667709/200000000 ≤ cos (323/3000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_5 : -19022943/1000000000 ≤ cos (9109/18000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_5 : cos (10757/15000 * π) ≤ -157614767/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_5 : cos (4243/30000 * π) ≤ 56431289/62500000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_5 : 944376369/1000000000 ≤ cos (8/75 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_6 : -8863369/200000000 ≤ cos (4627/9000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_6 : cos (129887/180000 * π) ≤ -641275549/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_6 : cos (50113/360000 * π) ≤ 905890599/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_6 : 945461737/1000000000 ≤ cos (1901/18000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_7 : -70452889/1000000000 ≤ cos (2351/4500 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_7 : cos (65357/90000 * π) ≤ -65228363/100000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_7 : cos (24643/180000 * π) ≤ 908923439/1000000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_7 : 473296499/500000000 ≤ cos (209/2000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_8 : -19447099/200000000 ≤ cos (531/1000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_8 : cos (131567/180000 * π) ≤ -3317477/5000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_8 : cos (48433/360000 * π) ≤ 91200203/100000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_8 : 947824063/1000000000 ≤ cos (1859/18000 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T1_9 : -62320289/500000000 ≤ cos (2429/4500 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_G_le_9 : cos (4139/5625 * π) ≤ -168730199/250000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem cos_sG_le_9 : cos (743/5625 * π) ≤ 457564313/500000000 := by
  refine cos_mul_pi_le 10 (p := 3.1415926535) (by norm_num) pi_ge_lo (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

theorem le_cos_T2_9 : 949096143/1000000000 ≤ cos (51/500 * π) := by
  refine le_cos_mul_pi 10 (p := 3.1415926536) pi_le_hi (by norm_num) (by norm_num) ?_
  simp only [cosT, Finset.sum_range_succ, Finset.sum_range_zero, Nat.factorial]
  norm_num

end Tammes15.Numerics
